version: '3.8'
services:
  nginx:
    image: nginx:1.17.3-alpine
    container_name: nginx
    ports:
      - "3443:3443"
      - "8443:8443"
    volumes:
      - ".docker/nginx/conf.d:/etc/nginx/conf.d"
      - ".docker/nginx/cert/localhost.pem:/etc/certs/localhost.pem"
      - ".docker/nginx/cert/localhost-key.pem:/etc/certs/localhost-key.pem"
    networks:
      fastpass-web:
        ipv4_address: 172.30.0.11

  front:
    container_name: front
    build:
      context: .
      target: dev-runner
      dockerfile: .docker/front/Dockerfile
    tty: true
    volumes:
      - ./src:/app
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    networks:
      fastpass-web:
        ipv4_address: 172.30.0.10

networks:
  fastpass-web:
    external: true