/**
 * HTTP Status Code
 */
export const HTTP_STATUS: Record<string, number> = {
  SUCCESS: 200,
  SUCCESS_CREATED: 201,
  BUD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
  SERVER_TEMPRORARILY_UNAVAILABLE: 503,
} as const;
